# Generated by Django 2.2.6 on 2019-10-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('project_model', models.CharField(max_length=50)),
                ('resource_count', models.IntegerField(default=0)),
            ],
        ),
    ]
