# Generated by Django 2.2.6 on 2019-10-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
